#!/bin/bash

# This file is public domain in the USA and all free countries.
# Elsewhere, consider it to be WTFPLv2. (wtfpl.net/txt/copying)

echo "Why hello there.
Would you like some tea (y/n)?"
read answer
[[ $answer =~ ^([yY][eE][sS]|[yY])$ ]] && echo "OK then, here you go: http://www.rivertea.com/blog/wp-content/uploads/2013/12/Green-Tea.jpg" || echo "OK then."
until [ "$SUCCESS" = "y" ] ;do
	echo 'Do you like Music? mykeyboardstartshere "Yass!" "No"'
	read answer
	case $answer in
		'Yass!') echo "Goody!";SUCCESS=y;;
		'No') echo "Well that's weird.";SUCCESS=y;;
		*) SUCCESS=n;;
	esac
done
exit
